### ISSUE TITLE
Make subgraph switchable precision

### ISSUE THREAD

**Issue by smitdylan2001** [oculus-samples/Unity-DepthAPI#37]
It would be good if the subgraph for urp has switchable precision. This uses single or half depending on in which shader it is used. This could give a small performance bump (and the hlsl code is already implemented I saw)

**Comment by TudorJude** [comment]
Hey smitdylan2001,

I believe that needs to run at full precision, otherwise we get some weird artifacts. If anything the half precision code in that hlsl file shouldn't have any place in there. I'll admit that before this subgraph, I hadn't ever touched shadergraph, so I took that code from some template. Will remove in a future commit.
