### ISSUE TITLE
URP shaders fail to compile Unity 6000.0.1f1

### ISSUE THREAD

**Issue by Squashi11** [oculus-samples/Unity-DepthAPI#40]
Using URP and the newest Unity 6 preview (6000.0.1f1), all shaders fail to compile (only occlusion particles simple lit compiles fine)
![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/70536593/fe1c07e1-7bfc-437e-a143-ac9f6297f8a0)

**Comment by Squashi11** [comment]
![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/70536593/36b1fef7-2bca-4107-8c75-31c8ab399ca6)
These are the errors present

**Comment by TudorJude** [comment]
Hey Squashi11,

I've found the issue. We've rewritten the unity shaders for both URP and BiRP to support occlusions. That SETUP_DEBUG_TEXTURE_DATA Macro has changed its signature on the Unity side, so any shader that was using it will break. My honest hope is that Unity will fix this once the full version is out. If not, we'll address the issue proper. For now, I will fix it in a different branch of this repo and update this thread.

**Comment by Squashi11** [comment]
I would like to personally thank you for your job! You saved my day with this fix <3. Greetings to Zürich

**Comment by TudorJude** [comment]
Try this branch, I've pushed the fixes here:

https://github.com/oculus-samples/Unity-DepthAPI/commits/unity6previewShadersFix/

Moving forward, we'll incorporate a more suitable fix into main branch.

**Comment by TudorJude** [comment]
I forgot to mention that installation of the package will be a bit different now, since the package is located on a different branch. I can give you two options:

* Download the packages folder with the two packages and then link them locally in your manifest.json file
* Follow this thread on how to change that git url to get the packages from a different branch https://forum.unity.com/threads/some-feedback-on-package-manager-git-support.743345/#post-8444525

**Comment by Squashi11** [comment]
Thanks a lot! Materials work now! I added hashtag with the branch name like this
https://github.com/oculus-samples/Unity-DepthAPI.git?path=/Packages/com.meta.xr.depthapi.urp#unity6previewShadersFix
Thanks for your support <3
