### ISSUE TITLE
Occluding shadows

### ISSUE THREAD

**Issue by Panek** [oculus-samples/Unity-DepthAPI#58]
Hello, is there any possibility to occlude shadows ?  If it is not currently supported, what would I have to do ?

![ezgif-3-f5bacbd2db](https://github.com/user-attachments/assets/3c7a4f6b-d46e-4e46-9779-23ae65c3b7b3)

**Comment by TudorJude** [comment]
Hello,

Yes, there is. What shader are you using for the floor there? It needs to support occlusions as well, since it is the material that actually draws shadows. I would guide you to [this repo of Phanto](https://github.com/oculus-samples/Unity-Phanto). It implements v67 occlusions and they have a solution in there in [this shader](https://github.com/oculus-samples/Unity-Phanto/blob/main/Assets/Phanto/Environment/Shaders/AlphaReceiveShadowMap.shader). You can either take inspiration from that shader, or simply use it as is and apply it to the material of your floor.

**Comment by Panek** [comment]
Thanks for the info ! I am using HighlightsAndShadows (from Meta/MRUK/Scene). Now I know what I need to do.
