### ISSUE TITLE
Occlusion support for URP ShaderGraph with Unity 6 preview

### ISSUE THREAD

**Issue by Squashi11** [oculus-samples/Unity-DepthAPI#61]
Hello there, I am unable to use occlusion Sub Graph with ShaderGraph. Even your provided solution in Meta Core SDK doesnt work. 
![image](https://github.com/user-attachments/assets/655436d7-fb11-4cfc-b28f-27df30993776)

**Comment by TudorJude** [comment]
Hello,

We've been recently made aware that our shadergraph node is not working properly after 2022.3.19. There's a new URP package that unity uses after that and it is affecting our subnode. It's likely that this is the same issue affecting Unity 6. We're actively looking into a solution.

**Comment by Squashi11** [comment]
Thanks for the feedback, will wait then.

**Comment by TudorJude** [comment]
Hello,

We've identified the problem. It has something to do with how Unity handles keywords in Shadergraph after a certain URP update. The official solution will be added in a future update of meta sdk core but until then here's what you should do to have it working. The OcclusionSubGraph needs a change. Since it's part of the core package you will have to duplicate it into your Assets folder in order to be able to alter it in any way and then rename it. 

Step 1: Duplicate the OcclusionSubGraph into your Asset folder and rename it to something else.
![image](https://github.com/user-attachments/assets/9e2057b7-cb6e-4bfa-a31b-f59bad5428ee)
***
Step 2: In the OcclusionSubGraph, you need to add the boolean keyword "SOFT_OCCLUSION" and set the values as shown in the following images.
![image](https://github.com/user-attachments/assets/506cf58a-3073-4cbf-98d4-9dae4a5ae22f)

<img width="395" alt="image" src="https://github.com/user-attachments/assets/a8f3a14a-dc9c-40d8-9341-0c1a87c72dfe">

***
Step 3: Repeat Step 2 but for the "HARD_OCCLUSION" keyword.
<img width="428" alt="image" src="https://github.com/user-attachments/assets/d0fd7f99-ef62-472b-8ec7-f4ead82c2a90">

***
Step 4: Replace OcclusionSubGraph in your ShaderGraphs with this one.

***

We haven't tested this in 6, but this should be the fix since whatever Unity fixed with these keywords has likely rippled into Unity 6.

This solution will be part of a future version of core, at which point you can replace this custom node with that, though, you're safe to just use this custom subgraph.

**Comment by Squashi11** [comment]
There seems to be some things missing in Unity 6, but other than that the setup is just the same 
![image](https://github.com/user-attachments/assets/8ebcd1a2-d15c-4445-9521-7c0a501402b8)
